//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idler.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idler.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-categorization feature initialization..
        /// </summary>
        public static string AutoCategorizationInitializationBackgroundTaskTitle {
            get {
                return ResourceManager.GetString("AutoCategorizationInitializationBackgroundTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-categorization feature failed to be initialized, it may not work properly..
        /// </summary>
        public static string AutoCategorizationInitializationFailureMessage {
            get {
                return ResourceManager.GetString("AutoCategorizationInitializationFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-categorization feature has been successfully setup..
        /// </summary>
        public static string AutoCategorizationInitializationSuccessMessage {
            get {
                return ResourceManager.GetString("AutoCategorizationInitializationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is being analyzed for auto-categorization feature..
        /// </summary>
        public static string AutoCategorizationModelBeingTrainedMessage {
            get {
                return ResourceManager.GetString("AutoCategorizationModelBeingTrainedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraining model for auto-categorization feature..
        /// </summary>
        public static string AutoCategorizationRetrainingBackgroundTaskTitle {
            get {
                return ResourceManager.GetString("AutoCategorizationRetrainingBackgroundTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraining of model for auto-categorization feature failed. The feature may not work properly..
        /// </summary>
        public static string AutoCategorizationRetrainingFailureMessage {
            get {
                return ResourceManager.GetString("AutoCategorizationRetrainingFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model for auto-categorization feature has been retrained..
        /// </summary>
        public static string AutoCategorizationRetrainingSuccessMessage {
            get {
                return ResourceManager.GetString("AutoCategorizationRetrainingSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrain NLP model.
        /// </summary>
        public static string RetrainAutoCategotizationModelPopupHeader {
            get {
                return ResourceManager.GetString("RetrainAutoCategotizationModelPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NLP model is busy.
        /// </summary>
        public static string RetrainAutoCategotizationModelPopupModelBusyText {
            get {
                return ResourceManager.GetString("RetrainAutoCategotizationModelPopupModelBusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trained on:.
        /// </summary>
        public static string RetrainAutoCategotizationModelPopupTrainedOnText {
            get {
                return ResourceManager.GetString("RetrainAutoCategotizationModelPopupTrainedOnText", resourceCulture);
            }
        }
    }
}
