name: Create Version Label

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - source/backend/**

jobs:
  create_label:
    name: Create Label
    uses: sergey-koryshev/build-system/.github/workflows/create-version-label.yml@create-version-label-v1.4.3
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_PAT }}
    with:
      project-type: Custom
      posh-custom-module-path: build/project-version-manager.psm1
      version-configuration-path: version-configuration.json
      scripts-ref: create-version-label-v1.4.3