name: Developer Build

run-name: Developer Build @${{ github.sha }}

on:
  workflow_run:
    workflows: [Create Version Label]
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  label_check:
    if: ${{ github.event_name == 'pull_request' }}
    name: Pull Request Label Checker
    uses: sergey-koryshev/build-system/.github/workflows/pr-label-checker.yml@create-version-label-v1.4.3
    with:
      version-configuration-path: version-configuration.json
      scripts-ref: create-version-label-v1.4.3
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    name: Build with Debug configuration
    uses: ./.github/workflows/build.yml
    with:
      build-configuration: Debug
      solution-path: src\Idler.sln
      build-path: src\Idler\bin\
