name: Developer Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs: 
  build:
    name: Build
    
    strategy:
      matrix:
        os: [windows-latest]
        platform: ['x64', 'x86']

    runs-on: ${{ matrix.os }}

    env:
      DotnetVersion: 6.0.x
      SolutionPath: src\Idler.sln
      BuildPath: src\Idler\bin\
      Configuration: Debug

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DotnetVersion }}
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Restore
        run: msbuild $env:SolutionPath /t:Restore /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ env.Configuration }}
          TargetPlatform: ${{ matrix.platform }}

      - name: Release Build
        run: msbuild $env:SolutionPath /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ env.Configuration }}
          TargetPlatform: ${{ matrix.platform }}
      
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: '.NET Build (${{ matrix.platform }})'
          path: ${{ env.BuildPath }}\${{ matrix.platform }}\${{ env.Configuration }}\*
