name: Developer Build

run-name: Developer Build @${{ github.sha }}

on:
  workflow_run:
    workflows: [Create Label]
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master
      - 'release/**'

jobs: 
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    name: Build with Debug configuration
    uses: ./.github/workflows/build.yml
    with:
      build-configuration: Debug
      solution-path: src\Idler.sln
      build-path: src\Idler\bin\
