name: Developer Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - release/**
jobs: 
  build:
    name: Build with Debug configuration
    uses: ./.github/workflows/build.yml
    with:
      build-configuration: Debug