name: release-build

on:

  push:

    branches:
      - master

jobs:

  release-build:

    strategy:
      matrix:
        os: [windows-latest]
        platform: ['x64', 'x86']

    runs-on: ${{ matrix.os }}

    env:
      DotnetVersion: 5.0.x
      SolutionPath: src\Idler.sln
      ReleaseBuildPath: src\Idler\bin\Release

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DotnetVersion }}
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Restore
        run: msbuild $env:SolutionPath /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: Debug

      - name: Release Build
        run: msbuild $env:SolutionPath /p:Configuration=$env:Configuration
        env:
          Configuration: Release
          TargetPlatform: ${{ matrix.platform }}
      
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: '.NET Build'
          path: ${{ env.ReleaseBuildPath }}\*
