name: release-build

on:
  push:
    branches:
      - master

jobs:
  release-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet build src/Idler.sln restore

      - name: Build
        run: dotnet build src/Idler.sln --configuration Release --no-restore

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ".NET Build"
          path: src/Idler/bin/Release/*
