name: Release Build

on:
 workflow_dispatch:
 push:
    branches:
      - release/**

jobs: 
  build:
    name: Build with Release configuration
    uses: ./.github/workflows/build.yml
    with:
      build-configuration: Release
      solution-path: src\Idler.sln
      build-path: src\Idler\bin\
