name: Release Build

on:
 workflow_dispatch:
 push:
    branches:
      - release/**

jobs:
  label_check:
    if: ${{ github.event_name == 'pull_request' }}
    name: Pull Request Label Checker
    uses: sergey-koryshev/build-system/.github/workflows/pr-label-checker.yml@create-version-label-v1.4.3
    with:
      version-configuration-path: version-configuration.json
      scripts-ref: create-version-label-v1.4.3
  build:
    name: Build with Release configuration
    uses: ./.github/workflows/build.yml
    with:
      build-configuration: Release
      solution-path: src\Idler.sln
      build-path: src\Idler\bin\
