name: Release Build

on:
  workflow_dispatch:
  push:
    branches:
      - release/**
jobs: 
  build:
    name: Build with Debug configuration
    uses: ./.github/workflows/build.yml
    with:
      build-configuration: Release