name: release-build

on:
  push:
    branches:
      - master

jobs:
  release-build:

    runs-on: windows-latest

    env:
      DotnetVersion: 5.0.x
      SolutionPath: src\Idler.sln

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DotnetVersion }}
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Restore
        run: msbuild $env:SolutionPath /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: Debug

      - name: Build the Windows Application Packaging Project (wapproj) 
        run: msbuild $env:SolutionPath /p:Configuration=$env:Configuration
        env:
          Configuration: Release
          TargetPlatform: "Any CPU"
